[package]
name = "uscreen-config"
version = "1.2.3"
edition = "2021"

[features]
default = ["storage", "commands", "platform-linux"]
storage = ["dep:tempfile"]
commands = ["dep:tempfile", "dep:tokio", "dep:libc"]
platform-linux = ["storage", "commands", "dep:libc", "dep:clap"]

[target.'cfg(target_os = "linux")'.dependencies]
libc = { version = "0.2", optional = true }

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }
serde_json = "1"
semver = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tempfile = { version = "3", optional = true }
tokio = { version = "1", optional = true, features = ["process", "time", "rt", "io-util", "macros"] }
